# config.py
import pygame
import math

# --- FPS 정의 ---
FPS = 60

# --- 상수 정의 ---
# 화면 크기
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# 맵 크기
MAP_WIDTH = 5000
MAP_HEIGHT = 5000

# 색상
GREEN = (0, 128, 0)
DARK_GREEN = (0, 100, 0)
BLUE = (0, 0, 255)
WHITE = (255, 255, 255)
SLIME_GREEN = (50, 200, 50)
RED = (255, 0, 0)
DARK_RED = (150, 0, 0)
HP_BAR_GREEN = (0, 200, 0)
DAGGER_COLOR = (200,200,0)
EXP_BAR_COLOR = (0, 150, 255)
EXP_ORB_COLOR = (100, 100, 255)
FLAIL_CHAIN_COLOR = (100, 100, 100)
FLAIL_HEAD_COLOR = (150, 150, 150)
UI_OPTION_BOX_BG_COLOR = (30, 30, 70)
UI_OPTION_BOX_BORDER_COLOR = (150, 150, 200)
WHIP_TRANSPARENT_COLOR = (220, 180, 100, 100)
BAT_COLOR = (40, 40, 40)
MINT_SLIME_COLOR = (170, 255, 200)
YELLOW = (255, 255, 0)

# 보스 슬라임 관련 색상
BOSS_SLIME_COLOR = (128, 0, 128)
BOSS_BULLET_COLOR = (75, 0, 130)
BOSS_MINION_SLIME_COLOR = (200, 100, 255)

# 폭풍 스킬 색상
STORM_COLOR = (173, 216, 230, 150)

# 플레이어 설정
PLAYER_SIZE = 30
PLAYER_SPEED = 5
PLAYER_INITIAL_HP = 100
PLAYER_INVINCIBILITY_DURATION = 60
PLAYER_INITIAL_LEVEL = 1
PLAYER_INITIAL_EXP_TO_LEVEL_UP = 8
PLAYER_DAMAGE_HITBOX_MULTIPLIER = 1.1

# 경험치 구슬 설정
EXP_ORB_RADIUS = 5
EXP_ORB_SPEED = 15
EXP_ORB_VALUE = 1
EXP_ORB_EXIST_CHECK_RADIUS = EXP_ORB_RADIUS * 2

# 잔디 설정
GRASS_PATCH_SIZE = 15
GRASS_TILE_SIZE = 60
GRASS_SPACING_FACTOR = 3

# 슬라임 설정
SLIME_RADIUS = 30
SLIME_SPEED = 3
SLIME_SPAWN_INTERVAL = 30
SPAWN_EDGE_OFFSET = 40
SLIME_INITIAL_BASE_HP = 10
SLIME_HP_BAR_WIDTH = 40
SLIME_HP_BAR_HEIGHT = 7
SLIME_DAMAGE_TO_PLAYER = 25
SLIME_LIFESPAN_SECONDS = 15
SLIME_HP_INCREASE_INTERVAL_SECONDS = 3

# 민트 슬라임 설정
MINT_SLIME_RADIUS_FACTOR = 0.75
MINT_SLIME_SPEED_FACTOR = 2.0

# 슈터 슬라임 설정
SHOOTER_SLIME_COLOR = YELLOW
SHOOTER_SLIME_SPEED_FACTOR = 0.5
SHOOTER_SLIME_SHOOT_COOLDOWN = FPS * 2
SLIME_BULLET_COLOR = (255, 165, 0)
SLIME_BULLET_SPEED = 12
SLIME_BULLET_LIFESPAN_SECONDS = 3
SLIME_BULLET_SIZE = 8
SLIME_BULLET_DAMAGE = 10

# 보스 슬라임 설정
BOSS_SLIME_RADIUS_MULTIPLIER = 5
BOSS_SLIME_HP_MULTIPLIER = 20
BOSS_SLIME_SPEED_MULTIPLIER = 1.2
BOSS_SLIME_REGEN_RATE_PER_SEC = 0.004 
BOSS_SLIME_CONTACT_DAMAGE = 50
BOSS_SLIME_SHOOT_COOLDOWN = FPS * 1.5
BOSS_SLIME_SPAWN_KILL_THRESHOLD = 150 
BOSS_MINION_SPAWN_COOLDOWN = FPS * 10
BOSS_MINION_SPAWN_COUNT = 2
BOSS_AWAKEN_COUNT = 2                   # 3번째 보스부터 각성 (0, 1, 2...)
BOSS_PHASE2_REGEN_MULT = 1.5            # 페이즈2 회복량 1.5배
BOSS_PHASE2_SPEED_MULT = 1.2            # 페이즈2 속도 1.2배
BOSS_SHOOTER_SUMMON_INTERVAL = 7 * FPS  # 7초마다 슈터 소환
BOSS_BIG_BULLET_INTERVAL = 4 * FPS      # 4초마다 거대 콩알탄

# 단검 설정
PLAYER_DAGGER_DAMAGE_BASE = 12
PLAYER_DAGGER_DAMAGE_MULTIPLIER_PER_LEVEL = 1.3
PLAYER_ATTACK_COOLDOWN = 60
DAGGER_SIZE = 15
DAGGER_SPEED = 10
DAGGER_LIFESPAN = 120

# 철퇴 설정
FLAIL_INITIAL_CHAIN_LENGTH = 80
FLAIL_HEAD_RADIUS = 15
FLAIL_ROTATION_SPEED = 0.05
FLAIL_DAMAGE_BASE = 20
FLAIL_DAMAGE_MULTIPLIER_PER_LEVEL = 1.25

# 박쥐 설정
BAT_SIZE = 10
BAT_WANDER_SPEED = 6
BAT_ATTACK_SPEED = 8
BAT_LIFESPAN_SECONDS = 20
BAT_BASE_DAMAGE = 7
BAT_LIFESTEAL_PERCENTAGE = 0.10
BAT_DETECTION_RADIUS = 250
BAT_ATTACK_COOLDOWN = FPS * 0.5
BAT_WANDER_RADIUS_FROM_PLAYER = 80
BAT_MAX_COUNT_INITIAL = 1
BAT_DAMAGE_MULTIPLIER_PER_LEVEL = 1.2
BAT_MAX_COUNT_INCREASE_PER_LEVEL = 1

# 폭풍 스킬 설정
STORM_SKILL_BASE_DAMAGE = 50
STORM_SKILL_COOLDOWN_SECONDS = 30
STORM_PROJECTILE_RADIUS = SLIME_RADIUS * 10
STORM_PROJECTILE_SPEED = 7
STORM_PROJECTILE_LIFESPAN_SECONDS = 4
STORM_SKILL_DAMAGE_INCREASE = 25
STORM_SKILL_COOLDOWN_DECREASE_SECONDS = 5
# config.py (맨 아래 JSONBIN 설정 부분)

SUPABASE_URL = "https://tkivnaupoklyxaomkaun.supabase.co"
SUPABASE_KEY = "sb_publishable_tikT725RvG9Q83sKmpr-IA_7PyNq6FK"